In [4]:
import numpy as np

In [3]:
num =[1,2,3]
print(type(num))

<class 'list'>


In [4]:
# vector
numv = np.array(num)
print(type(numv))
print(numv)

<class 'numpy.ndarray'>
[1 2 3]


In [5]:
numlist=[[1,2],[3,4]]
print(type(numlist))
#matrix
numma=np.array(numlist)
print(type(numma))
print(numma)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [7]:
print(numma.size)

4


In [28]:
import numpy as np

In [33]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [54]:
randarr = np.random.randint(1,50,20)
print(randarr)

[15 26 14  2 14 35 47 41 40 44 15 11 23 38 33 15  5 48 23 33]


In [47]:
maxnum = randarr.max()
minnum = randarr.min()
maxarg = randarr.argmax()
minarg = randarr.argmin()
print(minnum , "at ", minarg)
print(maxnum , "at " , maxarg)

2 at  2
49 at  5


In [55]:
rand2d = np.reshape(randarr,(2,10))
print(rand2d)

[[15 26 14  2 14 35 47 41 40 44]
 [15 11 23 38 33 15  5 48 23 33]]


In [59]:
print(np.shape(arr),arr.dtype)
print(np.shape(randarr),randarr.dtype)
print(np.shape(rand2d))

(25,) int64
(20,) int64
(2, 10)


In [ ]:
# 1D vector slicing and Indexing

In [5]:
a= np.arange(10)
print(a)
a[1]
ra = np.random.randint(1,10,5)
print(ra)
ra[1:3]

[0 1 2 3 4 5 6 7 8 9]
[6 9 5 9 8]


array([9, 5])

ra[1:3]=100

In [7]:
# value broadcasting
ra[1:3] = 100

In [9]:
print(ra) # avoid stack or heap Memory overflow

[  6 100 100   9   8]


In [ ]:
# 2D Matrix slicing and indexing

In [11]:
randmat = np.random.randn(5,5)

In [12]:
print(randmat)

[[ 0.45326421 -1.37891192  1.28614585 -0.03094046 -0.63134652]
 [-0.09781768  0.3553627   1.81113637 -0.22749238 -0.65477002]
 [ 0.55177854  0.6036429  -0.32948189  0.79441372  0.36392284]
 [ 1.29137215 -0.51218998 -1.04735916 -0.345037   -0.38789855]
 [-0.5396232   0.19419001  0.76756985  0.48963671 -1.38528724]]


In [15]:
print(randmat[0])

[ 0.45326421 -1.37891192  1.28614585 -0.03094046 -0.63134652]


In [16]:
print(randmat[0][1])

-1.3789119187614012


In [19]:
print(randmat[0,0])

0.45326420710977217


In [20]:
# slicing is important in image processing , Object recognition
print(randmat[0:2,0:2])

[[ 0.45326421 -1.37891192]
 [-0.09781768  0.3553627 ]]


In [21]:
print(randmat > 0)

[[ True False  True False False]
 [False  True  True False False]
 [ True  True False  True  True]
 [ True False False False False]
 [False  True  True  True False]]


In [22]:
print(randmat) # mask

[[ 0.45326421 -1.37891192  1.28614585 -0.03094046 -0.63134652]
 [-0.09781768  0.3553627   1.81113637 -0.22749238 -0.65477002]
 [ 0.55177854  0.6036429  -0.32948189  0.79441372  0.36392284]
 [ 1.29137215 -0.51218998 -1.04735916 -0.345037   -0.38789855]
 [-0.5396232   0.19419001  0.76756985  0.48963671 -1.38528724]]


In [23]:
res = randmat > 0

In [24]:
print(randmat[res]) # 

[0.45326421 1.28614585 0.3553627  1.81113637 0.55177854 0.6036429
 0.79441372 0.36392284 1.29137215 0.19419001 0.76756985 0.48963671]


In [27]:
print(randmat[randmat>0])

[0.45326421 1.28614585 0.3553627  1.81113637 0.55177854 0.6036429
 0.79441372 0.36392284 1.29137215 0.19419001 0.76756985 0.48963671]
